#include <Arduino.h>

#ifndef HARDWARE_H
#define HARDWARE_H

#define MAIN_LOOP_TIME 500U
#define STARTUP_TIME 2000U

#define R_TOP 46300U
#define R_BOTTOM 4600U
#define VCC 5.0f
#define MAX_SAMPLES 1023.0f

#define SCREEN_WIDTH 128U // OLED display width, in pixels
#define SCREEN_HEIGHT 64U // OLED display height, in pixels
#define OLED_RESET -1

#define DS18B20_ONE_WIRE_PIN 2
#define BATTERY_PIN A0
#define BATTERY_MUX_CHANNEL 0U
#define GEARBOX_PIN A1
#define GEARBOX_MUX_CHANNEL 1U

#define STARTUP_TEXT "BOOTING"
#define GEAR_N "N"
#define VOLTAGE_SIGN "V"
#define TEMPERATURE_SIGN "C"
#define TEMPERATURE_TITLE "T:"
#define READ_ERROR "ERR"
#define SUZUKI_TITLE "SUZUKI SV650S"
#define GITHUB_TEXT "github/midnight1337"


#define LOW_TEMPERATURE_THRESHOLD 5U
#define TEMPERATURE_ERROR_VALUE -273

#define LOW_BATTERY_THRESHOLD 12U
#define BATTERRY_LOW_LEVEL 12

#define GEAR_NEUTRAL_VALUE 0U
#define GEARBOX_INDETERMINATE_VOLTAGE 50
#define GEAR_THRESHOLD 15

#endif